Repository cse110-sp25-group16/cse110-sp25-group16, pull requests merged in 2025-05, with the labels that each got.

#22 docs(ADR): add Definition of Done
  admin/adr/0508-definition-of-done.md
Labels: documentation, management

#31 admin: Created phase1.png Diagram and phase1.md
  admin/cipipeline/phase1.drawio.png
  admin/cipipeline/phase1.md
Labels: ci/cd

#54 add ADR for MBTI integration
  specs/adrs/0518-mbti-integration.md
Labels: backend
